/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author aml05
 */
public class ChatGUI extends javax.swing.JFrame {

    /**
     * Creates new form SimpleChattingRoom
     */
    public ChatGUI() {
        initComponents();
        
        jOptionPane_name.setVisible(false);
                
        jTextArea_input.setEnabled(false);
        jTextArea_chat.setEnabled(false);
        jButton_send.setEnabled(false);
        
        jList_all_clients.removeAll(); // clears list
        jList_all_clients.setEnabled(false);
        jButton_chat.setEnabled(false);
        
        jButton_leave_server.setEnabled(false);
    }
    
    private Client client;
    
    private Server server;
    
    private Connection serverCxn;
    
    private boolean inChat = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel_chat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_chat = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_input = new javax.swing.JTextArea();
        jButton_send = new javax.swing.JButton();
        jPanel_chat1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_all_clients = new javax.swing.JList<>();
        jButton_chat = new javax.swing.JButton();
        jTextField_ip = new javax.swing.JTextField();
        jLabel_ip = new javax.swing.JLabel();
        jButton_server = new javax.swing.JButton();
        jButton_leave_server = new javax.swing.JButton();
        jLabel_error = new javax.swing.JLabel();
        jLabel_port_num = new javax.swing.JLabel();
        jTextField_port_num = new javax.swing.JTextField();
        jLabel_no_clients = new javax.swing.JLabel();
        jOptionPane_name = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_chat.setBorder(javax.swing.BorderFactory.createTitledBorder("Chatting Room"));

        jTextArea_chat.setColumns(20);
        jTextArea_chat.setRows(5);
        jScrollPane1.setViewportView(jTextArea_chat);

        jTextArea_input.setColumns(20);
        jTextArea_input.setRows(5);
        jScrollPane3.setViewportView(jTextArea_input);

        jButton_send.setBackground(new java.awt.Color(204, 204, 255));
        jButton_send.setText("send");
        jButton_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_chatLayout = new javax.swing.GroupLayout(jPanel_chat);
        jPanel_chat.setLayout(jPanel_chatLayout);
        jPanel_chatLayout.setHorizontalGroup(
            jPanel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_chatLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_send)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_chatLayout.setVerticalGroup(
            jPanel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_send))
                .addContainerGap())
        );

        jPanel_chat1.setBorder(javax.swing.BorderFactory.createTitledBorder("All Available Clients"));

        jList_all_clients.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList_all_clients);

        jButton_chat.setText("request");
        jButton_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_chat1Layout = new javax.swing.GroupLayout(jPanel_chat1);
        jPanel_chat1.setLayout(jPanel_chat1Layout);
        jPanel_chat1Layout.setHorizontalGroup(
            jPanel_chat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_chat1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel_chat1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton_chat)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel_chat1Layout.setVerticalGroup(
            jPanel_chat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_chat1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_chat)
                .addContainerGap())
        );

        jTextField_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipActionPerformed(evt);
            }
        });

        jLabel_ip.setText("IP Address:");

        jButton_server.setText("join");
        jButton_server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_serverActionPerformed(evt);
            }
        });

        jButton_leave_server.setBackground(new java.awt.Color(255, 102, 102));
        jButton_leave_server.setText("leave server");
        jButton_leave_server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_leave_serverActionPerformed(evt);
            }
        });

        jLabel_error.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_error.setText("No error(s)");

        jLabel_port_num.setText("Port Number:");

        jTextField_port_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_port_numActionPerformed(evt);
            }
        });

        jLabel_no_clients.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_no_clients.setText("No clients");

        jOptionPane_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_chat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_error, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel_port_num)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_port_num)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton_server))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel_ip)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_no_clients)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_leave_server)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jOptionPane_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_leave_server)
                            .addComponent(jLabel_no_clients))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_chat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_port_num)
                            .addComponent(jTextField_port_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_server))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel_error)
                        .addGap(147, 147, 147))
                    .addComponent(jPanel_chat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jOptionPane_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void jButton_sendActionPerformed(java.awt.event.ActionEvent evt) {                                             
        /*try {
            String input = jTextArea_input.getText();
            // client.getQueue().put(input);
        } catch (InterruptedException e) {
            jLabel_error.setText(e.getMessage());
        }
        */
    }                                            

    private void jButton_leave_serverActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        
    }                                                    

    private void jButton_chatActionPerformed(java.awt.event.ActionEvent evt) {                                             
//        try{
//            
//        } catch () {
//            
//        }
    }                                            

    private void jTextField_ipActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
    }                                             

    private void jTextField_port_numActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jButton_serverActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String ipAddr = jTextField_ip.getText();
        int portNum = 12345;
        
        try{
            portNum = Integer.parseInt(jTextField_port_num.getText());
        } catch (Exception e) {
            jLabel_error.setText("Port Number must be an integer value.");
        }
        
        String name;
        try {
            client = new Client(ipAddr, portNum);
            client.setServerIO(new String[0]);
            System.out.println("DONE");
            
            name = JOptionPane.showInputDialog(new JFrame(), "Enter your name");
            jOptionPane_name.setVisible(true);
            // client.getQueue().put(name);
            
            client.communicate();
            
//            serverCxn = new Connection(client, new String[0], portNum); 
            
        } catch (Exception e) {
            jLabel_error.setText(e.getMessage());
//            jLabel_error.setText("Unable to connect to Server. Check IP Address and/or Port Number.");
        } 
//        System.out.println("\rFINISHED");
            jLabel_error.setVisible(false);
            
        
            jList_all_clients.setEnabled(true);
            jList_all_clients.removeAll(); // clears list
            
            jButton_chat.setEnabled(true);

            jButton_leave_server.setEnabled(true);

    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatGUI().setVisible(true);
            }
        });
        
    }
    
    public String getClientName() {
        return JOptionPane.showInputDialog(new JFrame(), "Enter your name");
    }
    
    public JButton getjButton_chat() {
        return jButton_chat;
    }
    public JButton getjButton_leave_server() {
        return jButton_leave_server;
    }
    public JButton getjButton_send() {
        return jButton_send;
    }
    
    public JButton getjButton_server() {
        return jButton_server;
    }
    
    public JLabel getjLabel_error() {
        return jLabel_error;
    }
    
    public JLabel getjLabel_ip () {
        return jLabel_ip;
    }
    public JLabel getjLabel_port_num() {
        return jLabel_port_num;
    }
    
    public JList<String> getjList_all_clients() {
        return jList_all_clients;
    }
    
    public void setjList_all_clients(String[] list) {
        jList_all_clients = new JList<>(list);
    }
    
    public JPanel getjPanel_chat() {
        return jPanel_chat;
    }
    
    public JPanel getjPanel_chat1() {
        return jPanel_chat1;
    }
    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }
    
    public JTextArea getjTextArea_chat() {
        return jTextArea_chat;
    }
    public JTextArea getjTextArea_input() {
        return jTextArea_input;
    }
    
    public JTextField getjTextField_ip() {
        return jTextField_ip;
    }
    
    public JTextField getjTextField_port_num() {
        return jTextField_port_num;
    }
    
    public JLabel getjLabel_no_clients() {
        return jLabel_no_clients;
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_chat;
    private javax.swing.JButton jButton_leave_server;
    private javax.swing.JButton jButton_send;
    private javax.swing.JButton jButton_server;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JLabel jLabel_ip;
    private javax.swing.JLabel jLabel_no_clients;
    private javax.swing.JLabel jLabel_port_num;
    private javax.swing.JList<String> jList_all_clients;
    private javax.swing.JOptionPane jOptionPane_name;
    private javax.swing.JPanel jPanel_chat;
    private javax.swing.JPanel jPanel_chat1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea_chat;
    private javax.swing.JTextArea jTextArea_input;
    private javax.swing.JTextField jTextField_ip;
    private javax.swing.JTextField jTextField_port_num;
    // End of variables declaration                   
}
